name: Java CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      env:
         deployRepoUrl : ${{ secrets.deployRepoUrl }}
         deployRepoUsername : ${{ secrets.deployRepoUsername }}
         deployRepoPassword: ${{ secrets.deployRepoPassword }}
      run: ./gradlew build -DdeployRepoUrl=$deployRepoUrl -DdeployRepoUsername=$deployRepoUsername -DdeployRepoPassword=$1deployRepoPassword
